import {CodeValue} from "./code-value";
import { ContactPerson, ReferantDecision } from "./model.types";
import { BaseOperativeClaim } from "./base-operative-claim";

export interface BaseSuperClaim {
    readonly "@class": string;
    readonly className: string;
    readonly superClaimNum: number;
    readonly superClaimType: CodeValue;
    readonly superClaimStatus: CodeValue | null;
    readonly superClaimOrigStatus: CodeValue;
    readonly insuredProfessionAtEventDate: number;
    readonly insuredConfiscationFlag: boolean;
    readonly insuredAddressChange: boolean;
    readonly insuredDebt: boolean;
    readonly insuredDetailsChange: boolean;
    readonly insuredDetailsNotExist: boolean;
    readonly medicalEventDate: number;
    readonly eventDate: number;
    readonly calculationDate: number;
    readonly claimType: CodeValue;
    readonly claimCause: CodeValue;
    readonly firstAraivalDocAtAgentDate: number;
    readonly lastUpdateDate: number;
    readonly submitedBy: number;
    readonly automaticClaimFlag: boolean;
    readonly sendSMSFlag: boolean;
    readonly smsWasSentFlag: boolean;
    readonly maxForeclousreAmountToRelease: number;
    readonly nextStepType: CodeValue;
    readonly superClaimStatusReason: CodeValue;
    readonly superClaimStatusReferenceDate: number;
    readonly workerNum: number;
    readonly requestedExpertise: CodeValue;
    readonly superClaimCancelCloseType: number | null;
    readonly conversionFlag: boolean;
    readonly irregularSuperClaimFlag: boolean;
    readonly limitationCode: number;
    readonly needToCalculateType: number;
    readonly needToRefreshData: boolean;
    readonly firstDocArrivalDate: number;
    // readonly operativeClaims: BaseOperativeClaim[];
    readonly referantDecision: ReferantDecision;
    readonly contactPersons: readonly (ContactPerson)[];
    readonly superClaimCancelCloseDesc: string;
    readonly openingReason: CodeValue;
    readonly hospitalAdmissionStartDate: number;
    readonly hospitalAdmissionEndDate: number;
    readonly submitionMethod: CodeValue;
    readonly additionalInjuryTypes: CodeValue[];
    readonly workingStatus: number;
    readonly accommodationType: number;
    readonly otherClaimResult: number;
    readonly illnessImprovement: number;
    readonly handledBy: number;
    readonly suspicionExist: number;
    readonly otherActiveClaim: boolean;
    readonly familyHeadConfiscationFlag: boolean;
}
