import {Model} from "../model";
import { DocumentsPackage, Insured, ISODateTimeString, Modify, ProcessType, ScaledNumber, Transmission } from "./model.types";
export interface BaseProcess {
    readonly "@class": string;
    readonly id: number;
  readonly module: string;
    readonly version: number;
  readonly processKey: string;
  readonly creationDate: ISODateTimeString;
  readonly lastModify: Modify;
    readonly status: number;
  readonly step: number;
  readonly stepName: string;
  readonly taskName: string;
  readonly taskId: string;
  readonly taskCreationDate: ISODateTimeString;
  readonly taskIdPrevious: string;
  readonly taskNamePrevious: string;
  readonly selectedTab: string;
  readonly  processType: ProcessType;
  readonly company: string;
  readonly transmission: Transmission;
  readonly insured: Insured;
  readonly documentsPackage: DocumentsPackage;
  readonly creatorId: ScaledNumber;
  readonly clerkSerialNum: ScaledNumber;
      readonly clerkId: ScaledNumber;
    readonly messages: Model.Message[];
  readonly kycIncomeSourceRequired: boolean;
  readonly kycIndirect: boolean;
  readonly kycRequired: boolean;
  readonly isInsuredVerified: boolean;
  readonly isDocoumentArrived: boolean;
}
